version: '3'

services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - '4000:3000'
    environment:
      DATABASE_URL: postgresql://umami:umami@umami-db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: borzolini-clinic-analytics-2024
    depends_on:
      - umami-db
    restart: always
    networks:
      - umami-network

  umami-db:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - umami-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - umami-network

  # New PostgreSQL service for your clinic app
  clinic-db:
    image: postgres:15-alpine
    ports:
      - '5432:5432' # Standard PostgreSQL port
    environment:
      POSTGRES_DB: borzolini_clinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - clinic-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - clinic-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=clinic-cluster
      - node.name=clinic-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    networks:
      - clinic-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Kibana for Elasticsearch management (optional)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: always
    networks:
      - clinic-network

volumes:
  umami-db-data:
  clinic-db-data:
  elasticsearch-data:

networks:
  umami-network:
    driver: bridge
  clinic-network:
    driver: bridge
